version: "3"

services:
  eze-db:
    image: mongo:latest
    container_name: "eze-db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db
    expose:
      - ${MONGO_PORT}

volumes:
  mongodb_data_container:
